name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate GitHub Snake SVG - Matrix Style
        uses: Platane/snk@v3
        with:
          github_user_name: frnadin
          outputs: dist/github-contribution-grid-snake.svg
          color_snake: "#39FF14"
          color_dots: "#111111,#0a0a0a,#1a1a1a,#222222,#2a2a2a"
          background: "#000000" 

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
